# Generated by Django 3.2 on 2021-04-30 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_alter_quiz_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_answer', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.answer')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='answer',
            field=models.ManyToManyField(through='training.ResultAnswer', to='training.Answer'),
        ),
        migrations.AddField(
            model_name='result',
            name='quiz',
            field=models.ManyToManyField(to='training.Quiz'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
