# Generated by Django 3.2 on 2021-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_quizdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdomain',
            name='manual',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quizdomain',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quizdomain',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
