# Generated by Django 3.2 on 2021-05-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210507_1142'),
    ]

    operations = [
    ]
